export enum FormElementType {
  text = 1,
  number = 2,
  textarea = 3,
  date = 4,
  email = 5,
  password = 6,
  search = 7,
  tel = 8,
  url = 9,
  time = 10,
  datetimeLocal = 11,
  file = 12,
  radio = 13,
  checkbox = 14,
  toggle = 15,
  selectClient = 16,
  selectServer = 17,
}
